genk:
	g++ -std=c++11 -w -lm Timer.cpp Timer2.cpp GraphMatrix.cpp GraphUtils.cpp Isomorphism.cpp Random.cpp nauty/nauty.c nauty/nautil.c nauty/naugraph.c IGtrie.cpp Label.cpp Fase.cpp DynamicGraph.cpp GenSubgInv.cpp -o genk -pthread


k3:
	g++ -std=c++11 -w -lm Timer.cpp Timer2.cpp GraphMatrix.cpp GraphUtils.cpp Isomorphism.cpp Random.cpp nauty/nauty.c nauty/nautil.c nauty/naugraph.c IGtrie.cpp Label.cpp Fase.cpp DynamicGraph.cpp K3.cpp -o k3 -pthread

